# #####################################################################
# Automatically generated by qmake (2.01a) Thu Apr 24 17:50:12 2008
# #####################################################################
TEMPLATE = subdirs

# Directories
SUBDIRS += core \
    cscope \
    app
CONFIG += debug_and_release
