/***************************************************************************
 *   Copyright (C) 2007-2008 by Elad Lahav
 *   elad_lahav@users.sourceforge.net
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the
 *   Free Software Foundation, Inc.,
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 ***************************************************************************/

#ifndef __CSCOPE_CROSSREF_H
#define __CSCOPE_CROSSREF_H

#include "engine.h"
#include "cscope.h"

namespace KScope
{

namespace Cscope
{

/**
 * Manages a Cscope cross-reference database.
 * The cross-reference database generated by Cscope is stored in a cscope.out
 * file, as well as optional inverted-index files. This class creates
 * independent Cscope processes used to query and build these files. When
 * building the cross-reference database, Cscope uses temporary files, so that
 * the existing database can still be queried.
 * @author Elad Lahav
 */
class Crossref : public Core::Engine
{
	Q_OBJECT

public:
	Crossref(QObject* parent = 0);
	~Crossref();

	void open(const QString&);

	/**
	 * @return The current status of the database.
	 */
	Status status() const { return status_; }

public slots:
	void query(Core::Engine::Connection&, const Core::Query&) const;
	void build(Core::Engine::Connection&) const;

	const QString& path() { return path_; }

private:
	/**
	 * The path of the directory containing the cscope.out file.
	 */
	QString path_;

	/**
	 * Command-line arguments to Cscope.
	 */
	QStringList args_;

	/**
	 * The current status of the database.
	 */
	Status status_;

private slots:
	void buildProcessFinished(int, QProcess::ExitStatus);
};

}

}

#endif // __CSCOPE_CROSSREF_H
